[package]
name = "teleport"
version = "0.2.5"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
byteorder = "1.4.3"
